hello-request-post = { action = "*-post-object", res = "/dec_app/9tGpLNnfhjHxqiTKDCpgAipBVh4qjCDjxYGsUEy5p5EZ/32768", group = { location = "outer" }, access = "accept" }
hello-response-post = { action = "*-post-object", res = "/dec_app/9tGpLNnfhjHxqiTKDCpgAipBVh4qjCDjxYGsUEy5p5EZ/32769", group = { location = "outer" }, access = "accept" }

